# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\tmypackage\x1a\x1fgoogle/protobuf/timestamp.proto\"L\n\rNestedMessage\x12\x0f\n\x07str_val\x18\x01 \x01(\t\x12*\n\x06ts_val\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xe8\x04\n\x07Message\x12\x12\n\ndouble_val\x18\x01 \x01(\x01\x12\x11\n\tfloat_val\x18\x02 \x01(\x02\x12\x11\n\tint32_val\x18\x03 \x01(\x05\x12\x11\n\tint64_val\x18\x04 \x01(\x03\x12\x12\n\nuint32_val\x18\x05 \x01(\r\x12\x12\n\nuint64_val\x18\x06 \x01(\x04\x12\x12\n\nsint32_val\x18\x07 \x01(\x11\x12\x12\n\nsint64_val\x18\x08 \x01(\x12\x12\x13\n\x0b\x66ixed32_val\x18\t \x01(\x07\x12\x13\n\x0b\x66ixed64_val\x18\n \x01(\x06\x12\x14\n\x0csfixed32_val\x18\x0b \x01(\x0f\x12\x14\n\x0csfixed64_val\x18\x0c \x01(\x10\x12\x10\n\x08\x62ool_val\x18\r \x01(\x08\x12\x12\n\nstring_val\x18\x0e \x01(\t\x12\x11\n\tbytes_val\x18\x0f \x01(\x0c\x12#\n\x08\x65num_val\x18\x10 \x01(\x0e\x32\x11.mypackage.MyEnum\x12\x31\n\rtimestamp_val\x18\x11 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1a\n\x12repeated_int32_val\x18\x12 \x03(\x05\x12\x32\n\x10repeated_msg_val\x18\x13 \x03(\x0b\x32\x18.mypackage.NestedMessage\x12;\n\x0estr_to_msg_map\x18\x14 \x03(\x0b\x32#.mypackage.Message.StrToMsgMapEntry\x1aL\n\x10StrToMsgMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\'\n\x05value\x18\x02 \x01(\x0b\x32\x18.mypackage.NestedMessage:\x02\x38\x01*<\n\x06MyEnum\x12\x17\n\x13MY_ENUM_UNSPECIFIED\x10\x00\x12\x07\n\x03\x46OO\x10\x01\x12\x07\n\x03\x42\x41R\x10\x02\x12\x07\n\x03\x42\x41Z\x10\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE_STRTOMSGMAPENTRY']._loaded_options = None
  _globals['_MESSAGE_STRTOMSGMAPENTRY']._serialized_options = b'8\001'
  _globals['_MYENUM']._serialized_start=758
  _globals['_MYENUM']._serialized_end=818
  _globals['_NESTEDMESSAGE']._serialized_start=61
  _globals['_NESTEDMESSAGE']._serialized_end=137
  _globals['_MESSAGE']._serialized_start=140
  _globals['_MESSAGE']._serialized_end=756
  _globals['_MESSAGE_STRTOMSGMAPENTRY']._serialized_start=680
  _globals['_MESSAGE_STRTOMSGMAPENTRY']._serialized_end=756
# @@protoc_insertion_point(module_scope)
