"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _MyEnum:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _MyEnumEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_MyEnum.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    MY_ENUM_UNSPECIFIED: _MyEnum.ValueType  # 0
    FOO: _MyEnum.ValueType  # 1
    BAR: _MyEnum.ValueType  # 2
    BAZ: _MyEnum.ValueType  # 3

class MyEnum(_MyEnum, metaclass=_MyEnumEnumTypeWrapper): ...

MY_ENUM_UNSPECIFIED: MyEnum.ValueType  # 0
FOO: MyEnum.ValueType  # 1
BAR: MyEnum.ValueType  # 2
BAZ: MyEnum.ValueType  # 3
global___MyEnum = MyEnum

@typing.final
class NestedMessage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STR_VAL_FIELD_NUMBER: builtins.int
    TS_VAL_FIELD_NUMBER: builtins.int
    str_val: builtins.str
    @property
    def ts_val(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        str_val: builtins.str = ...,
        ts_val: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["ts_val", b"ts_val"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["str_val", b"str_val", "ts_val", b"ts_val"]) -> None: ...

global___NestedMessage = NestedMessage

@typing.final
class Message(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing.final
    class StrToMsgMapEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: builtins.str
        @property
        def value(self) -> global___NestedMessage: ...
        def __init__(
            self,
            *,
            key: builtins.str = ...,
            value: global___NestedMessage | None = ...,
        ) -> None: ...
        def HasField(self, field_name: typing.Literal["value", b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing.Literal["key", b"key", "value", b"value"]) -> None: ...

    DOUBLE_VAL_FIELD_NUMBER: builtins.int
    FLOAT_VAL_FIELD_NUMBER: builtins.int
    INT32_VAL_FIELD_NUMBER: builtins.int
    INT64_VAL_FIELD_NUMBER: builtins.int
    UINT32_VAL_FIELD_NUMBER: builtins.int
    UINT64_VAL_FIELD_NUMBER: builtins.int
    SINT32_VAL_FIELD_NUMBER: builtins.int
    SINT64_VAL_FIELD_NUMBER: builtins.int
    FIXED32_VAL_FIELD_NUMBER: builtins.int
    FIXED64_VAL_FIELD_NUMBER: builtins.int
    SFIXED32_VAL_FIELD_NUMBER: builtins.int
    SFIXED64_VAL_FIELD_NUMBER: builtins.int
    BOOL_VAL_FIELD_NUMBER: builtins.int
    STRING_VAL_FIELD_NUMBER: builtins.int
    BYTES_VAL_FIELD_NUMBER: builtins.int
    ENUM_VAL_FIELD_NUMBER: builtins.int
    TIMESTAMP_VAL_FIELD_NUMBER: builtins.int
    REPEATED_INT32_VAL_FIELD_NUMBER: builtins.int
    REPEATED_MSG_VAL_FIELD_NUMBER: builtins.int
    STR_TO_MSG_MAP_FIELD_NUMBER: builtins.int
    double_val: builtins.float
    float_val: builtins.float
    int32_val: builtins.int
    int64_val: builtins.int
    uint32_val: builtins.int
    uint64_val: builtins.int
    sint32_val: builtins.int
    sint64_val: builtins.int
    fixed32_val: builtins.int
    fixed64_val: builtins.int
    sfixed32_val: builtins.int
    sfixed64_val: builtins.int
    bool_val: builtins.bool
    string_val: builtins.str
    bytes_val: builtins.bytes
    enum_val: global___MyEnum.ValueType
    @property
    def timestamp_val(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def repeated_int32_val(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def repeated_msg_val(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___NestedMessage]: ...
    @property
    def str_to_msg_map(self) -> google.protobuf.internal.containers.MessageMap[builtins.str, global___NestedMessage]: ...
    def __init__(
        self,
        *,
        double_val: builtins.float = ...,
        float_val: builtins.float = ...,
        int32_val: builtins.int = ...,
        int64_val: builtins.int = ...,
        uint32_val: builtins.int = ...,
        uint64_val: builtins.int = ...,
        sint32_val: builtins.int = ...,
        sint64_val: builtins.int = ...,
        fixed32_val: builtins.int = ...,
        fixed64_val: builtins.int = ...,
        sfixed32_val: builtins.int = ...,
        sfixed64_val: builtins.int = ...,
        bool_val: builtins.bool = ...,
        string_val: builtins.str = ...,
        bytes_val: builtins.bytes = ...,
        enum_val: global___MyEnum.ValueType = ...,
        timestamp_val: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        repeated_int32_val: collections.abc.Iterable[builtins.int] | None = ...,
        repeated_msg_val: collections.abc.Iterable[global___NestedMessage] | None = ...,
        str_to_msg_map: collections.abc.Mapping[builtins.str, global___NestedMessage] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["timestamp_val", b"timestamp_val"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["bool_val", b"bool_val", "bytes_val", b"bytes_val", "double_val", b"double_val", "enum_val", b"enum_val", "fixed32_val", b"fixed32_val", "fixed64_val", b"fixed64_val", "float_val", b"float_val", "int32_val", b"int32_val", "int64_val", b"int64_val", "repeated_int32_val", b"repeated_int32_val", "repeated_msg_val", b"repeated_msg_val", "sfixed32_val", b"sfixed32_val", "sfixed64_val", b"sfixed64_val", "sint32_val", b"sint32_val", "sint64_val", b"sint64_val", "str_to_msg_map", b"str_to_msg_map", "string_val", b"string_val", "timestamp_val", b"timestamp_val", "uint32_val", b"uint32_val", "uint64_val", b"uint64_val"]) -> None: ...

global___Message = Message
